### ISSUE TITLE
0.2版本更新啥了，文件大了很多啊，看上去实现了很强大的功能

### ISSUE THREAD

**Issue by TonyLi2013** [Duysi/Warcraft-3-MH#1]
如题~

**Comment by Duysi** [comment]
增加的内容你试试不就知道了 主要是增加 小地图ping 英雄数字显血 ------------------&nbsp;Original&nbsp;------------------

**Comment by TonyLi2013** [comment]
我肯定第一时间下载了去尝试啊，可惜download之后会自动被系统自带的检测删除，根本没给我机会，是不是没过杀毒？
